package pe.edu.unsch.entities;
// Generated 16/07/2019 10:12:52 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "divisimabd")
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private String nombre;
	private String direccion;
	private int celular;

	public Cliente() {
	}

	public Cliente(int idcliente, String nombre, String direccion, int celular) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.celular = celular;
	}

	@Id

	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "celular", nullable = false)
	public int getCelular() {
		return this.celular;
	}

	public void setCelular(int celular) {
		this.celular = celular;
	}

}
