package pe.edu.unsch.entities;
// Generated 16/07/2019 10:12:52 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "divisimabd")
public class Marca implements java.io.Serializable {

	private int idmarca;
	private String nombre;

	public Marca() {
	}

	public Marca(int idmarca, String nombre) {
		this.idmarca = idmarca;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idmarca", unique = true, nullable = false)
	public int getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(int idmarca) {
		this.idmarca = idmarca;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
