package pe.edu.unsch.entities;
// Generated 16/07/2019 10:12:52 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "divisimabd")
public class Producto implements java.io.Serializable {

	private int idproducto;
	private String nombre;
	private String precio;
	private String cantidad;
	private String descripcion;
	private String urlimagen;
	private String caracteristicas;

	public Producto() {
	}

	public Producto(int idproducto, String nombre, String precio, String cantidad, String descripcion, String urlimagen,
			String caracteristicas) {
		this.idproducto = idproducto;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.urlimagen = urlimagen;
		this.caracteristicas = caracteristicas;
	}

	@Id

	@Column(name = "idproducto", unique = true, nullable = false)
	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false, length = 45)
	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	@Column(name = "cantidad", nullable = false, length = 45)
	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "urlimagen", nullable = false, length = 45)
	public String getUrlimagen() {
		return this.urlimagen;
	}

	public void setUrlimagen(String urlimagen) {
		this.urlimagen = urlimagen;
	}

	@Column(name = "caracteristicas", nullable = false, length = 45)
	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

}
